# opt-in to Travis's newer/faster container-based infrastructure
sudo: false

language: scala

scala:
 - 2.11.11
 - 2.11.12
 - 2.12.4

script:
 - sbt ++$TRAVIS_SCALA_VERSION update doc

jdk:
 - oraclejdk8

before_cache:
 - find $HOME/.sbt -name "*.lock" | xargs rm
 - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm

cache:
  directories:
   - $HOME/.ivy2/cache
   - $HOME/.sbt/boot
   - $HOME/.sbt/launchers
